# Generated by Django 4.2.5 on 2024-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('writer', 'Writer'), ('actor', 'Actor')], null=True, verbose_name='role'),
        ),
    ]
