# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.services.idp_grpc import user_info_pb2 as src_dot_services_dot_idp__grpc_dot_user__info__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/services/idp_grpc/user_info_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserInfoStub(object):
    """python -m grpc_tools.protoc -Igrpc_api=grpc_api/protos --python_out=grpc_api --pyi_out=grpc_api --grpc_python_out=grpc_api grpc_api/protos/user_info.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/UserInfo/GetUser',
                request_serializer=src_dot_services_dot_idp__grpc_dot_user__info__pb2.GetUserRequest.SerializeToString,
                response_deserializer=src_dot_services_dot_idp__grpc_dot_user__info__pb2.Info.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.stream_stream(
                '/UserInfo/GetAllUsers',
                request_serializer=src_dot_services_dot_idp__grpc_dot_user__info__pb2.GetUserRequest.SerializeToString,
                response_deserializer=src_dot_services_dot_idp__grpc_dot_user__info__pb2.Info.FromString,
                _registered_method=True)


class UserInfoServicer(object):
    """python -m grpc_tools.protoc -Igrpc_api=grpc_api/protos --python_out=grpc_api --pyi_out=grpc_api --grpc_python_out=grpc_api grpc_api/protos/user_info.proto

    """

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=src_dot_services_dot_idp__grpc_dot_user__info__pb2.GetUserRequest.FromString,
                    response_serializer=src_dot_services_dot_idp__grpc_dot_user__info__pb2.Info.SerializeToString,
            ),
            'GetAllUsers': grpc.stream_stream_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=src_dot_services_dot_idp__grpc_dot_user__info__pb2.GetUserRequest.FromString,
                    response_serializer=src_dot_services_dot_idp__grpc_dot_user__info__pb2.Info.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserInfo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserInfo(object):
    """python -m grpc_tools.protoc -Igrpc_api=grpc_api/protos --python_out=grpc_api --pyi_out=grpc_api --grpc_python_out=grpc_api grpc_api/protos/user_info.proto

    """

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserInfo/GetUser',
            src_dot_services_dot_idp__grpc_dot_user__info__pb2.GetUserRequest.SerializeToString,
            src_dot_services_dot_idp__grpc_dot_user__info__pb2.Info.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/UserInfo/GetAllUsers',
            src_dot_services_dot_idp__grpc_dot_user__info__pb2.GetUserRequest.SerializeToString,
            src_dot_services_dot_idp__grpc_dot_user__info__pb2.Info.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
