apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-statefulset
spec:
  serviceName: elasticsearch-service
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-app
    spec:
      containers:
        - name: elasticsearch-container
          image: elasticsearch:8.6.2
          envFrom:
{{ toYaml .Values.envFrom | indent 12 }}
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
              name: es-cli
          volumeMounts:
            - mountPath: "/usr/share/elasticsearch/data"
              name: elasticsearch-volume
      # https://stackoverflow.com/questions/73871100/elasticsearch-crashloopbackoff-when-deploying-with-eck-in-kubernetes-okd-4-11
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: elasticsearch-volume
          persistentVolumeClaim:
            claimName: elasticsearch-pvc

  selector:
    matchLabels:
      app: elasticsearch-app