apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-statefulset
spec:
  serviceName: minio-service
  replicas: 1
  template:
    metadata:
      labels:
        app: minio-app
    spec:
      containers:
        - name: minio-container
          image: minio/minio
          envFrom:
{{ toYaml .Values.envFrom | indent 12 }}
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: minio-ui
          volumeMounts:
            - mountPath: "/data"
              name: minio-volume
          command: ["minio", "server", "--console-address", ":9001", "/data"]
      volumes:
        - name: minio-volume
          persistentVolumeClaim:
            claimName: minio-pvc

  selector:
    matchLabels:
      app: minio-app