apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo-cli
          volumeMounts:
            - mountPath: "/data/db"
              name: mongo-volume
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc

  selector:
    matchLabels:
      app: mongo-app