apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
spec:
  serviceName: redis-service
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
              name: redis-cli
          volumeMounts:
            - mountPath: "/data"
              name: redis-volume
          command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-pvc

  selector:
    matchLabels:
      app: redis-app