{{ $def := get .Values.storage .Values.storage.kind }}
{{ $storageSize := $def.size -}}
{{ $pods := keys .Values.storage.pods | sortAlpha }}
{{ range $index, $podName := $pods }}
---
{{ $pod := get $.Values.storage.pods $podName }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $podName }}-pvc
  labels:
    app: {{ $.Chart.Name }}
spec:
  accessModes:
    - {{ $pod.mode }}
  resources:
    requests:
      storage: {{ $pod.size | default $def.size }}
  {{- if $def.volumes }}
  volumeName: {{ $podName }}-pv 
  {{- end }}
  storageClassName: {{ $def.class }}
{{ end }}