{{- if eq .Values.storage.kind "cloud" }}
{{- $storageSize := .Values.storage.local.size }}
{{- range $index, $pod := .Values.storage.pods }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-pv
spec:
  capacity:
    storage: 4Gi
  storageClassName: "yc-network-hdd"
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: epdt13t41isrit225vdv
{{- end }}
{{- end }}