{{ if eq .Values.storage.kind "cloud" }}
{{ $storageSize := .Values.storage.cloud.size }}
{{ range $index, $pod := .Values.storage.pods }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-pv
spec:
  capacity:
    storage: {{ $storageSize }}
  storageClassName: {{ $.Values.storage.cloud.class }}
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: {{ $.Values.storage.cloud.volumeHandle }}
{{ end }}
{{ end }}