version: '3.7'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app
#    depends_on:
#      - db
#      - minio

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=practicum
      - MINIO_ROOT_PASSWORD=StrongPass
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data


#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - app

volumes:
  postgres_data:
  minio_storage:

