# Generated by Django 4.2.13 on 2024-05-26 18:06

import movies.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_personfilmwork_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="file",
            field=models.FileField(
                null=True, storage=movies.custom_storage.CustomStorage(), upload_to="", verbose_name="file"
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[("director", "Director"), ("writer", "Writer"), ("actor", "Actor")],
                max_length=30,
                null=True,
                verbose_name="role",
            ),
        ),
    ]
