apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
        - name: admin-container
          image: k8s-admin:latest
          envFrom:
            - configMapRef:
                name: api-configs
            - secretRef:
                name: api-prod-env
          env:
          - name: DEBUG
            value: "True"         
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
  selector:
    matchLabels:
      app: admin-app