apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  type: ClusterIP
  selector:
    app: jaeger-app
  ports:
    - protocol: TCP
      port: 6831
      name: jaeger-tcp
    - protocol: UDP
      port: 6831
      name: jaeger-udp
    - protocol: TCP
      port: 16686
      name: jaeger-ui