apiVersion: batch/v1
kind: Job
metadata:
  name: pginit-job
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: pginit-container
        image: k8s-pginit:latest
        envFrom:
          - configMapRef:
              name: api-configs
          - secretRef:
              name: api-prod-env
        imagePullPolicy: IfNotPresent
      restartPolicy: Never