version: '3'
services:
  postgres:
    image: postgres:13
    volumes:
      - dbstorage:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - esstorage:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4g -Xmx4g

  redis:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisstorage:/data

volumes:
  dbstorage:
    name: admin-panel-db
    external: true
  esstorage:
    name: admin-panel-es
    external: true
  redisstorage:
    name: admin-panel-redis
    external: true
