version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - dbstorage-idp:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    env_file: [.env]

  idp:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file: [.env]

  keycloak:
    build:
      context: keycloak
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file: [.env]

volumes:
  dbstorage-idp:
