version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - dbstorage-idp:/var/lib/postgresql/data
    restart: always
    env_file: [.env]

  idp:
    build:
      context: .
    depends_on:
      - postgres
    env_file: [.env]

  keycloak:
    build:
      context: keycloak
    depends_on:
      - postgres
    env_file: [.env]

volumes:
  dbstorage-idp:
