apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  type: ClusterIP
  selector:
    app: mailhog-app
  ports:
    - protocol: TCP
      port: 8025
      name: mailhog-ui
    - protocol: TCP
      port: 1025
      name: mailhog-tcp