apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mailhog-app
    spec:
      containers:
        - name: mailhog-container
          image: mailhog/mailhog
          envFrom:
            - configMapRef:
                name: api-configs
            - secretRef:
                name: api-prod-env
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8025
            - containerPort: 1025
  selector:
    matchLabels:
      app: mailhog-app