apiVersion: v1
kind: Service
metadata:
  name: idp-service
spec:
  type: ClusterIP
  selector:
    app: idp-app
  ports:
    - protocol: TCP
      port: 80
      name: idp-http
    - protocol: TCP
      port: 50051
      name: idp-grpc